import type { RuneStave } from "./types";

export const RUNES: RuneStave[] = [
  {
    id: "fehu",
    glyph: "ᚠ",
    name: "Fehu",
    phonetic: "F",
    meaning: "Cattle and movable wealth — what can be spent, stolen, or given.",
    positions: [
      { x: 36, y: 18 },
      { x: 36, y: 50 },
      { x: 36, y: 82 },
      { x: 66, y: 30 },
      { x: 66, y: 58 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [0, 3],
      [1, 4],
    ],
  },
  {
    id: "uruz",
    glyph: "ᚢ",
    name: "Uruz",
    phonetic: "U",
    meaning: "Aurochs — raw strength that does not ask permission.",
    positions: [
      { x: 32, y: 22 },
      { x: 68, y: 22 },
      { x: 68, y: 78 },
    ],
    links: [
      [0, 1],
      [1, 2],
    ],
  },
  {
    id: "thurisaz",
    glyph: "ᚦ",
    name: "Thurisaz",
    phonetic: "Th",
    meaning: "Thurs — the thorn, the giant, the necessary wound.",
    positions: [
      { x: 34, y: 18 },
      { x: 34, y: 50 },
      { x: 34, y: 82 },
      { x: 68, y: 50 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [1, 3],
    ],
  },
  {
    id: "ansuz",
    glyph: "ᚨ",
    name: "Ansuz",
    phonetic: "A",
    meaning: "A god's mouth — speech that binds, names, and opens.",
    positions: [
      { x: 34, y: 18 },
      { x: 34, y: 50 },
      { x: 34, y: 82 },
      { x: 66, y: 32 },
      { x: 66, y: 62 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [0, 3],
      [1, 4],
    ],
  },
  {
    id: "raidho",
    glyph: "ᚱ",
    name: "Raidho",
    phonetic: "R",
    meaning: "The ride — a road that must be taken, not discussed.",
    positions: [
      { x: 34, y: 16 },
      { x: 34, y: 50 },
      { x: 34, y: 84 },
      { x: 66, y: 30 },
      { x: 62, y: 68 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [0, 3],
      [1, 4],
    ],
  },
  {
    id: "kenaz",
    glyph: "ᚲ",
    name: "Kenaz",
    phonetic: "K",
    meaning: "The torch — a controlled fire that shows the work.",
    positions: [
      { x: 32, y: 24 },
      { x: 50, y: 50 },
      { x: 68, y: 76 },
    ],
    links: [
      [0, 1],
      [1, 2],
    ],
  },
  {
    id: "gebo",
    glyph: "ᚷ",
    name: "Gebo",
    phonetic: "G",
    meaning: "The gift — exchange that leaves both parties changed.",
    positions: [
      { x: 26, y: 20 },
      { x: 74, y: 20 },
      { x: 50, y: 50 },
      { x: 26, y: 80 },
      { x: 74, y: 80 },
    ],
    links: [
      [0, 2],
      [2, 4],
      [1, 2],
      [2, 3],
    ],
  },
  {
    id: "wunjo",
    glyph: "ᚹ",
    name: "Wunjo",
    phonetic: "W",
    meaning: "Joy as kinship — the hall when the feud is quiet.",
    positions: [
      { x: 34, y: 18 },
      { x: 34, y: 50 },
      { x: 34, y: 82 },
      { x: 66, y: 34 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [0, 3],
    ],
  },
  {
    id: "hagalaz",
    glyph: "ᚺ",
    name: "Hagalaz",
    phonetic: "H",
    meaning: "Hail — the storm that ruins the crop and clears the field.",
    positions: [
      { x: 28, y: 18 },
      { x: 28, y: 82 },
      { x: 50, y: 50 },
      { x: 72, y: 18 },
      { x: 72, y: 82 },
    ],
    links: [
      [0, 1],
      [3, 4],
      [0, 2],
      [2, 3],
    ],
  },
  {
    id: "naudhiz",
    glyph: "ᚾ",
    name: "Naudhiz",
    phonetic: "N",
    meaning: "Need-fire — constraint that teaches the real cost.",
    positions: [
      { x: 32, y: 78 },
      { x: 50, y: 50 },
      { x: 68, y: 22 },
    ],
    links: [
      [0, 1],
      [1, 2],
    ],
  },
  {
    id: "isa",
    glyph: "ᛁ",
    name: "Isa",
    phonetic: "I",
    meaning: "Ice — stillness that holds, and will not be hurried.",
    positions: [
      { x: 50, y: 20 },
      { x: 50, y: 50 },
      { x: 50, y: 80 },
    ],
    links: [
      [0, 1],
      [1, 2],
    ],
  },
  {
    id: "jera",
    glyph: "ᛃ",
    name: "Jera",
    phonetic: "J",
    meaning: "Year — harvest that arrives only after the work.",
    positions: [
      { x: 34, y: 32 },
      { x: 66, y: 32 },
      { x: 34, y: 68 },
      { x: 66, y: 68 },
    ],
    links: [
      [0, 1],
      [2, 3],
      [1, 2],
    ],
  },
  {
    id: "eihwaz",
    glyph: "ᛇ",
    name: "Eihwaz",
    phonetic: "Ei",
    meaning: "Yew — the spine between life and the other side.",
    positions: [
      { x: 64, y: 16 },
      { x: 36, y: 34 },
      { x: 50, y: 50 },
      { x: 64, y: 66 },
      { x: 36, y: 84 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
    ],
  },
  {
    id: "perthro",
    glyph: "ᛈ",
    name: "Perthro",
    phonetic: "P",
    meaning: "The lot-cup — chance, the unborn, what is still in the cup.",
    positions: [
      { x: 36, y: 22 },
      { x: 36, y: 50 },
      { x: 36, y: 78 },
      { x: 68, y: 50 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [0, 3],
      [3, 2],
    ],
  },
  {
    id: "algiz",
    glyph: "ᛉ",
    name: "Algiz",
    phonetic: "Z",
    meaning: "Elk-sedge — a ward, a reaching upward, a hand that guards.",
    positions: [
      { x: 50, y: 18 },
      { x: 50, y: 50 },
      { x: 50, y: 82 },
      { x: 26, y: 40 },
      { x: 74, y: 40 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [1, 3],
      [1, 4],
    ],
  },
  {
    id: "sowilo",
    glyph: "ᛊ",
    name: "Sowilo",
    phonetic: "S",
    meaning: "Sun — victory as a sudden clear road.",
    positions: [
      { x: 62, y: 20 },
      { x: 38, y: 38 },
      { x: 62, y: 62 },
      { x: 38, y: 80 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [2, 3],
    ],
  },
  {
    id: "tiwaz",
    glyph: "ᛏ",
    name: "Tiwaz",
    phonetic: "T",
    meaning: "Týr's mark — justice that costs a hand.",
    positions: [
      { x: 50, y: 18 },
      { x: 28, y: 36 },
      { x: 72, y: 36 },
      { x: 50, y: 58 },
      { x: 50, y: 84 },
    ],
    links: [
      [1, 0],
      [0, 2],
      [0, 3],
      [3, 4],
    ],
  },
  {
    id: "berkano",
    glyph: "ᛒ",
    name: "Berkano",
    phonetic: "B",
    meaning: "Birch — birth, shelter, the green that returns.",
    positions: [
      { x: 34, y: 16 },
      { x: 34, y: 50 },
      { x: 34, y: 84 },
      { x: 66, y: 34 },
      { x: 66, y: 66 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [0, 3],
      [1, 4],
    ],
  },
  {
    id: "ehwaz",
    glyph: "ᛖ",
    name: "Ehwaz",
    phonetic: "E",
    meaning: "Horse — two wills moving as one, or failing to.",
    positions: [
      { x: 30, y: 24 },
      { x: 30, y: 76 },
      { x: 70, y: 24 },
      { x: 70, y: 76 },
    ],
    links: [
      [0, 1],
      [2, 3],
      [0, 2],
    ],
  },
  {
    id: "mannaz",
    glyph: "ᛗ",
    name: "Mannaz",
    phonetic: "M",
    meaning: "Man — the self among others, the face you owe the hall.",
    positions: [
      { x: 28, y: 22 },
      { x: 28, y: 78 },
      { x: 50, y: 50 },
      { x: 72, y: 22 },
      { x: 72, y: 78 },
    ],
    links: [
      [0, 1],
      [3, 4],
      [0, 2],
      [2, 3],
    ],
  },
  {
    id: "laguz",
    glyph: "ᛚ",
    name: "Laguz",
    phonetic: "L",
    meaning: "Water — the deep that carries, drowns, and dreams.",
    positions: [
      { x: 38, y: 20 },
      { x: 38, y: 50 },
      { x: 38, y: 80 },
      { x: 66, y: 34 },
    ],
    links: [
      [0, 1],
      [1, 2],
      [0, 3],
    ],
  },
  {
    id: "ingwaz",
    glyph: "ᛜ",
    name: "Ingwaz",
    phonetic: "Ng",
    meaning: "Ing — stored seed, the closed field before it opens.",
    positions: [
      { x: 50, y: 22 },
      { x: 28, y: 50 },
      { x: 72, y: 50 },
      { x: 50, y: 78 },
    ],
    links: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 3],
    ],
  },
  {
    id: "dagaz",
    glyph: "ᛞ",
    name: "Dagaz",
    phonetic: "D",
    meaning: "Day — the hinge where night and morning trade places.",
    positions: [
      { x: 24, y: 24 },
      { x: 24, y: 76 },
      { x: 50, y: 50 },
      { x: 76, y: 24 },
      { x: 76, y: 76 },
    ],
    links: [
      [0, 1],
      [3, 4],
      [0, 2],
      [2, 4],
      [3, 2],
      [2, 1],
    ],
  },
  {
    id: "othala",
    glyph: "ᛟ",
    name: "Othala",
    phonetic: "O",
    meaning: "Ancestral land — what you inherit, and what inherits you.",
    positions: [
      { x: 50, y: 20 },
      { x: 28, y: 44 },
      { x: 72, y: 44 },
      { x: 36, y: 80 },
      { x: 64, y: 80 },
    ],
    links: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 4],
    ],
  },
];

export function runeById(id: string): RuneStave {
  return RUNES.find((r) => r.id === id) ?? RUNES[0]!;
}
